messages: #Сообщения плагина
  not-loaded: "§cВаши данные еще не загрузились! Попробуйте чуть позже..." #Если эндерсундук не успел загрузиться с файла а игрок пытается его открыть
  no-points: "§cУ вас не хватает поинтов!" #Если у игрока недостаточно валюты для покупки слота
  successfull-buy: "§aУспешная покупка!" #Сообщение при успешной покупке слота

title: "§lВаш Эндер Сундук" #Название меню
max-size: 6 #1 - 9 слотов, 2 - 18 слотов, 3 - 27 слотов, 4 - 36 слотов, 5 - 45 слотов, 6 - 54 слота.
start-size: 27 #Сколько слотов доступно в начале, НЕ ОБЯЗАТЕЛЬНО должно делиться на 9
economy-type: PlayerPoints #или Vault

namespaced: kitten-enderchest-slotprice #NamespacedKey для PersistentDataContainer. НЕ ИЗМЕНЯЙТЕ И НЕ УДАЛЯЙТЕ ЭТУ СТРОЧКУ, ЕСЛИ НЕ ЗНАЕТЕ ЧТО ЭТО ОЗНАЧАЕТ!!!

lock-items: #Список предметов для блокировки слота
#  example: #Пример предмета для блокировки слота (НИ В КОЕМ СЛУЧАЕ НЕ НАЗЫВАЙТЕ EXAMPLE!!! НАЗЫВАЙТЕ ЧИСЛОМ ОБОЗНАЧАЮЩИМ СЛОТ ДЛЯ КОТОРОГО ПРЕДНАЗНАЧЕН ПРЕДМЕТ!
#    material: barrier #По умолчанию: barrier
#    amount: 1 #По умолчанию: 1
#    displayname: "§x§f§f§0§0§0§0§lСЛОТ ЗАБЛОКИРОВАН!" #По умолчанию: ""
#    lore:  #По умолчанию: null
#      - " "
#      - " §fДанный слот вам §x§f§f§0§0§0§0§nнедоступен§r§f!"
#      - " §fНо вы можете его купить за §6100 поинтов!"
#      - " §f§nНажмите, чтобы купить прямо сейчас!"
#      - " "
#    model: 0 #По умолчанию: 0
#    price: 100 #По умолчанию: 1
  "27": #Если в списке предметов для блокировки слота нет предмета для определенного слота, будет использован ближайший предмет с более маленьким слотом
    displayname: "§x§f§f§0§0§0§0§lСЛОТ ЗАБЛОКИРОВАН!"
    lore:
      - " "
      - " §fДанный слот вам §x§f§f§0§0§0§0§nнедоступен§r§f!"
      - " §fНо вы можете его купить за §6100 поинтов!"
      - " §f§nНажмите, чтобы купить прямо сейчас!"
      - " "
    price: 100
  "36":
    displayname: "§x§f§f§0§0§0§0§lСЛОТ ЗАБЛОКИРОВАН!"
    lore:
      - " "
      - " §fДанный слот вам §x§f§f§0§0§0§0§nнедоступен§r§f!"
      - " §fНо вы можете его купить за §6200 поинтов!"
      - " §f§nНажмите, чтобы купить прямо сейчас!"
      - " "
    price: 200
  "45":
    displayname: "§x§f§f§0§0§0§0§lСЛОТ ЗАБЛОКИРОВАН!"
    lore:
      - " "
      - " §fДанный слот вам §x§f§f§0§0§0§0§nнедоступен§r§f!"
      - " §fНо вы можете его купить за §6300 поинтов!"
      - " §f§nНажмите, чтобы купить прямо сейчас!"
      - " "
    price: 300